### ISSUE TITLE
./build.sh: line 85: cargo: command not found

### ISSUE THREAD

**Issue by Melchior1410** [wofferl/proxmox-backup-arm64#17]
Hello,
I always get the error when running:

> Note: switching to 'ce6def219262b5c1f6dbe5440f9f90038bafb3d8'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at ce6def2 bump version to 0.9.7-1
> Cloning into 'perlmod'...
> remote: Enumerating objects: 1441, done.
> remote: Total 1441 (delta 0), reused 0 (delta 0), pack-reused 1441
> Receiving objects: 100% (1441/1441), 238.19 KiB | 3.35 MiB/s, done.
> Resolving deltas: 100% (980/980), done.
> HEAD is now at f8b49fc clippy fixups
> fatal: reference is not a tree: 9488180f9ef3bf57e049b645c001c3df9b65e11c
> patching file .cargo/config
> patching file Makefile
> patching file pmg-rs/Cargo.toml
> patching file pmg-rs/debian/control
> patching file pve-rs/Cargo.toml
> patching file pve-rs/debian/control
> patching file proxmox-apt/Cargo.toml
> patching file proxmox-openid-rs/Cargo.toml
> ./build.sh: line 85: cargo: command not found

What am I doing wrong?

**Comment by wofferl** [comment]
You are missing the rust binaries. Did you follow the steps in the Readme before starting the build script?

**Install build essentials and dependencies**

 apt-get -y install \
	build-essential curl sudo git lintian \
	pkg-config libudev-dev libssl-dev libapt-pkg-dev libclang-dev \
	libnetaddr-ip-perl libpam0g-dev libcurl4-openssl-dev

**Install rustup**

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s
source ~/.cargo/env

**Comment by Melchior1410** [comment]
Yes, I followed everything as described.

> pi@pbs:~/proxmox-backup-arm64 $ sudo apt-get -y install build-essential curl sudo git lintian pkg-config libudev-dev libssl-dev libapt-pkg-dev libclang-dev libnetaddr-ip-perl libpam0g-dev libcurl4-openssl-dev
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> libapt-pkg-dev is already the newest version (2.2.4).
> build-essential is already the newest version (12.9).
> curl is already the newest version (7.74.0-1.3+deb11u3).
> libcurl4-openssl-dev is already the newest version (7.74.0-1.3+deb11u3).
> git is already the newest version (1:2.30.2-1).
> libnetaddr-ip-perl is already the newest version (4.079+dfsg-1+b5).
> lintian is already the newest version (2.104.0).
> libclang-dev is already the newest version (1:11.0-51+nmu5).
> pkg-config is already the newest version (0.29.2-1).
> sudo is already the newest version (1.9.5p2-3).
> libudev-dev is already the newest version (247.3-7+deb11u1).
> libpam0g-dev is already the newest version (1.4.0-9+deb11u1+rpt2).
> libssl-dev is already the newest version (1.1.1n-0+deb11u3+rpt1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> pi@pbs:~/proxmox-backup-arm64 $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s
> source ~/.cargo/env
> info: downloading installer
> 
> Welcome to Rust!
> 
> This will download and install the official compiler for the Rust
> programming language, and its package manager, Cargo.
> 
> Rustup metadata and toolchains will be installed into the Rustup
> home directory, located at:
> 
>   /home/pi/.rustup
> 
> This can be modified with the RUSTUP_HOME environment variable.
> 
> The Cargo home directory is located at:
> 
>   /home/pi/.cargo
> 
> This can be modified with the CARGO_HOME environment variable.
> 
> The cargo, rustc, rustup and other commands will be added to
> Cargo's bin directory, located at:
> 
>   /home/pi/.cargo/bin
> 
> This path will then be added to your PATH environment variable by
> modifying the profile files located at:
> 
>   /home/pi/.profile
>   /home/pi/.bashrc
> 
> You can uninstall at any time with rustup self uninstall and
> these changes will be reverted.
> 
> Current installation options:
> 
> 
>    default host triple: aarch64-unknown-linux-gnu
>      default toolchain: stable (default)
>                profile: default
>   modify PATH variable: yes
> 
> 1) Proceed with installation (default)
> 2) Customize installation
> 3) Cancel installation
> >1
> 
> info: profile set to 'default'
> info: default host triple is aarch64-unknown-linux-gnu
> warning: Updating existing toolchain, profile choice will be ignored
> info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
> info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'
> 
>   stable-aarch64-unknown-linux-gnu unchanged - rustc 1.65.0 (897e37553 2022-11-02)
> 
> 
> Rust is installed now. Great!
> 
> To get started you may need to restart your current shell.
> This would reload your PATH environment variable to include
> Cargo's bin directory ($HOME/.cargo/bin).
> 
> To configure your current shell, run:
> source "$HOME/.cargo/env"
> pi@pbs:~/proxmox-backup-arm64 $ sudo ./build.sh
> pve-eslint up-to-date
> dpkg-query: no packages found matching libproxmox-rs-perl
> Removing perlmod/
> Removing proxmox-acme-rs/
> Removing proxmox-apt/
> Removing proxmox-openid-rs/
> Removing proxmox/
> HEAD is now at 9488180 pmg-rs: bump to 0.6.2
> HEAD is now at 9488180 pmg-rs: bump to 0.6.2
> Cloning into 'proxmox'...
> remote: Enumerating objects: 11488, done.
> remote: Total 11488 (delta 0), reused 0 (delta 0), pack-reused 11488
> Receiving objects: 100% (11488/11488), 1.84 MiB | 8.07 MiB/s, done.
> Resolving deltas: 100% (6727/6727), done.
> HEAD is now at 208d4ff bump proxmox-section-config to 1.0.1-1
> Note: switching to '2ae95b5f4e9870113dab8fea1df631299559d4a4'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at 2ae95b5 metrics: bump to 0.2.1
> Cloning into 'proxmox-acme-rs'...
> remote: Enumerating objects: 250, done.
> remote: Total 250 (delta 0), reused 0 (delta 0), pack-reused 250
> Receiving objects: 100% (250/250), 48.31 KiB | 1.46 MiB/s, done.
> Resolving deltas: 100% (164/164), done.
> HEAD is now at ff3fceb jws: allocate exact capacity
> Note: switching to 'abc0bdd09d5c3501534510d49da0ae8fa5c05c05'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at abc0bdd bump version to 0.4.0
> Cloning into 'proxmox-apt'...
> remote: Enumerating objects: 443, done.
> remote: Total 443 (delta 0), reused 0 (delta 0), pack-reused 443
> Receiving objects: 100% (443/443), 11.21 MiB | 9.07 MiB/s, done.
> Resolving deltas: 100% (275/275), done.
> HEAD is now at 8a7a719 bump version to 0.9.3-1
> Note: switching to '6c0c48b97a29cac1519402e4a1c77010e8a5d216'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at 6c0c48b bump version to 0.9.2-1
> Cloning into 'proxmox-openid-rs'...
> remote: Enumerating objects: 238, done.
> remote: Total 238 (delta 0), reused 0 (delta 0), pack-reused 238
> Receiving objects: 100% (238/238), 32.26 KiB | 1.08 MiB/s, done.
> Resolving deltas: 100% (124/124), done.
> HEAD is now at ce6def2 bump version to 0.9.7-1
> Note: switching to 'ce6def219262b5c1f6dbe5440f9f90038bafb3d8'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at ce6def2 bump version to 0.9.7-1
> Cloning into 'perlmod'...
> remote: Enumerating objects: 1441, done.
> remote: Total 1441 (delta 0), reused 0 (delta 0), pack-reused 1441
> Receiving objects: 100% (1441/1441), 238.19 KiB | 4.18 MiB/s, done.
> Resolving deltas: 100% (980/980), done.
> HEAD is now at f8b49fc clippy fixups
> fatal: reference is not a tree: 9488180f9ef3bf57e049b645c001c3df9b65e11c
> patching file .cargo/config
> patching file Makefile
> patching file pmg-rs/Cargo.toml
> patching file pmg-rs/debian/control
> patching file pve-rs/Cargo.toml
> patching file pve-rs/debian/control
> patching file proxmox-apt/Cargo.toml
> patching file proxmox-openid-rs/Cargo.toml
> ./build.sh: line 85: cargo: command not found
> pi@pbs:~/proxmox-backup-arm64 $

**Comment by wofferl** [comment]
After installing rustup the cargo binary should be located in ~/.cargo/bin/
It is necessary that this Path is in your PATH environment, which is done, by sourcing ~/cargo/env.

Can you check your PATH and the cargo bin library, if all is in place?

**Comment by Melchior1410** [comment]
I'm a little further now. User rights were incorrect.
Now a new problem:

> HEAD is now at ce6def2 bump version to 0.9.7-1
> Cloning into 'perlmod'...
> remote: Enumerating objects: 1441, done.
> remote: Total 1441 (delta 0), reused 0 (delta 0), pack-reused 1441
> Receiving objects: 100% (1441/1441), 238.19 KiB | 3.26 MiB/s, done.
> Resolving deltas: 100% (980/980), done.
> HEAD is now at f8b49fc clippy fixups
> fatal: reference is not a tree: 9488180f9ef3bf57e049b645c001c3df9b65e11c
> patching file .cargo/config
> patching file Makefile
> patching file pmg-rs/Cargo.toml
> patching file pmg-rs/debian/control
> patching file pve-rs/Cargo.toml
> patching file pve-rs/debian/control
> patching file proxmox-apt/Cargo.toml
> patching file proxmox-openid-rs/Cargo.toml
> error: failed to load manifest for workspace member `/proxmox-backup-arm64/sources/proxmox-perl-rs/pve-rs`
> 
> Caused by:
>   failed to load manifest for dependency `perlmod`
> 
> Caused by:
>   failed to read `/proxmox-backup-arm64/sources/perlmod/perlmod/Cargo.toml`
> 
> Caused by:
>   No such file or directory (os error 2)
