### ISSUE TITLE
Shell Issue (Connection failed (Code: 1006)

### ISSUE THREAD

**Issue by rooskie94** [wofferl/proxmox-backup-arm64#25]
Got pbs installed on my pi and backups are working. Greatly appreciate this.
My only issue is when trying to access the shell on the web client
Connection failed (Code: 1006).

If you have any tips or fixes let me know. Thanks!

**Comment by rooskie94** [comment]
No errors except "xtermjs: starting" 
Ive used firefox, chrome and even cleared cache and data. Have a local PVE and no issues. 
No proxy, everything is LAN.
Worse case I can try to reinstall it again or continue researching. But thought Id let you know.

**Comment by wofferl** [comment]
Which version of pve-xtermjs do you have installed?
Is the file /usr/bin/termproxy present?

**Comment by rooskie94** [comment]
/usr/bin/termproxy is not present. 
Ive tried searching in root and proxmox dir and no luck finding xterm version and using xterm -version prints 
-bash: xterm: command not found
Make me wonder if something happened during install.

**Comment by wofferl** [comment]
xterm is not the problem here.

You need the ./pve-xtermjs_*_arm64.deb package. This is also build with the build.sh script and should be in the packages directory.
Look at the README which packages you need to install for the proxmox-backup-server installation.

**Comment by rooskie94** [comment]
My bad, found pve-xtermjs_4.16.0-1_arm64.deb in packages
