### ISSUE TITLE
compiling error 

### ISSUE THREAD

**Issue by Leo-wq** [wofferl/proxmox-backup-arm64#26]
somewhere while compiling the process aborts. Unfortunately, I can't narrow it down exactly, so I recorded and attached the entire output of the shell... the last time (3 months ago) everything ran smoothly.
Or does it also have to be compiled on an ARM64 system?
[log.txt](https://github.com/wofferl/proxmox-backup-arm64/files/10925313/log.txt)

**Comment by MAFLO321** [comment]
On what architecture have you tried to build it?

Yes, you have to build it on an arm64 debian bullseye.
This can be a real device or use for example qemu with an arm64-chroot.

**Comment by Leo-wq** [comment]
good evening, it was my fault... at least partly. I've now compiled it on my ARM RockPro64 and it ran through to the end.
In between there were still errors when compiling (see photo, I know, not quite as nice but I couldn't attach it as text on the fly)
![PXL_20230309_204755284](https://user-images.githubusercontent.com/52599092/224170776-bb7a2322-6892-473d-a2f4-306733bf86fb.jpg)

**Comment by MAFLO321** [comment]
Okay nice.
The warnings are always there and come from the documentation generation. These should to be fixed upstream. So be not too nervous about these warnings.
