### ISSUE TITLE
PBS 2.3-3 Shell Connection failed (Code 1006)

### ISSUE THREAD

**Issue by Leo-wq** [wofferl/proxmox-backup-arm64#27]
Hello, I am now running PBS on a RockPro64 with Linux 5.10.0-21-arm64 #1 SMP Debian 5.10.162-1.

So far everything works fine, except that I can't open the shell. the above error always comes up... any clues where I could start?

**Comment by wofferl** [comment]
Have you installed the pve-xtermjs packet? (see #25)

**Comment by Leo-wq** [comment]
yes, all packages listed in the guide were installed, including pve-xtermjs_4.16.0-1_arm64.deb.

**Comment by wofferl** [comment]
Then it may be a problem with the websocket request.

wss://ip:8007/api2/json/nodes/localhost/vncwebsocket

Can you check your browsers debug console, if the request is blocked or has an error?

Which browser do you use?
Do you use a proxy?

**Comment by Leo-wq** [comment]
this is what appears:

```
parameter verification errors

parameter 'port': parameter is missing and it is not optional.
parameter 'vncticket': parameter is missing and it is not optional.
```

i tried with Edge and Brave.

Curiously, PVE's shell works fine.

**Comment by Dentax** [comment]
> 

Same for me. Fresh Installation on RPi 4 - Kernel: Linux 5.15.84-v8+ #1613 SMP PREEMPT 

![image](https://user-images.githubusercontent.com/5037918/224475611-8375efdb-bdfc-48ee-90e2-cf4a0deb8d30.png)

**Comment by wofferl** [comment]
Does calling termproxy --help on the console work?
Is there anything about termproxy in the syslog?

Can you check the browser network log to see if the websocket call is correct?
Are the parameters port and vncticket set?

It should look like this:

wss://192.168.0.1:8007/api2/json/nodes/localhost/vncwebsocket?port=44719&vncticket=PBSTERM........

**Comment by Dentax** [comment]
termproxy --help doesn't work. 

![image](https://user-images.githubusercontent.com/5037918/224481034-90aea395-9256-4bcf-bad2-075224aa9874.png)

On browser network log its called:

![image](https://user-images.githubusercontent.com/5037918/224481110-3dbfee6a-39df-4513-b533-2e33c6b07c97.png)
![image](https://user-images.githubusercontent.com/5037918/224481174-85fe0071-3803-4a51-8517-8b66f85a9549.png)

**Comment by wofferl** [comment]
The termproxy binary is missing or not in binary path.

Can you look if the pve-xtermjs is installed correctly and the binary is in PATH.
dpkg -s pve-xtermjs
dpkg -L pve-xtermjs

**Comment by Leo-wq** [comment]
for me it looks like xterms is installed correctly...


> xxxxxxxxx@pbs:~ termproxy --help
> -bash: termproxy: Kommando nicht gefunden.
> xxxxxxxx@pbs:~$ dpkg -s pve-xtermjs
> Package: pve-xtermjs
> Status: install ok installed
> Priority: optional
> Section: admin
> Installed-Size: 1503
> Maintainer: Proxmox Support Team <support@proxmox.com>
> Architecture: arm64
> Multi-Arch: allowed
> Source: rust-termproxy
> Version: 4.16.0-1
> Description: HTML/JS Shell client for Proxmox projects
>  This package provides an xterm.js client/proxy for Proxmoxprojects'  Hosts,
>  Proxmox VE containers or Proxmox VE VM's serial-terminals.
> Homepage: https://www.proxmox.com)
> 


> xxxxxxxxx@pbs:~ dpkg -L pve-xtermjs
> /.
> /usr
> /usr/share
> /usr/share/doc
> /usr/share/doc/pve-xtermjs
> /usr/share/doc/pve-xtermjs/SOURCE
> /usr/share/doc/pve-xtermjs/changelog.Debian.gz
> /usr/share/doc/pve-xtermjs/copyright
> /usr/share/pve-xtermjs
> /usr/share/pve-xtermjs/index.html.hbs
> /usr/share/pve-xtermjs/index.html.tpl
> /usr/share/pve-xtermjs/main.js
> /usr/share/pve-xtermjs/style.css
> /usr/share/pve-xtermjs/util.js
> /usr/share/pve-xtermjs/xterm-addon-fit.js
> /usr/share/pve-xtermjs/xterm-addon-fit.js.map
> /usr/share/pve-xtermjs/xterm.css
> /usr/share/pve-xtermjs/xterm.js
> /usr/share/pve-xtermjs/xterm.js.map
> xxxxxxxxxx@pbs:~$

**Comment by wofferl** [comment]
The termproxy binary (/usr/bin/termproxy) is missing in your pve-xtermjs package. 
Can you rebuild it and see if you get any errors during the build?

**Comment by Leo-wq** [comment]
How can I compile only the xterm package, or do I have to compile them all again?

**Comment by wofferl** [comment]
You can remove or rename the pve-xtermjs package in the packages folder and start the build.sh again.

or go to source/pve-xtermjs and compile it from there with:
`make deb`

**Comment by Leo-wq** [comment]
Okay thanks. I'll try it out as soon as the backup has been restored... 4 tb already need more than 23h, from hdd from ssd... Something doesn't fit again 🤦🏼‍♂️ but that's another matter

**Comment by Leo-wq** [comment]
there are only a few warnings, no errors:

> make[1]: Entering directory '/root/proxmox-backup-arm64/sources/pve-xtermjs'
dh binary
   dh_prep
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
dpkg-gencontrol: warning: Depends field of package pve-xtermjs: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: Depends field of package pve-xtermjs: substitution variable ${cargo:Depends} used, but is not defined
dpkg-gencontrol: warning: Recommends field of package pve-xtermjs: substitution variable ${cargo:Recommends} used, but is not defined
dpkg-gencontrol: warning: Suggests field of package pve-xtermjs: substitution variable ${cargo:Suggests} used, but is not defined
dpkg-gencontrol: warning: Provides field of package pve-xtermjs: substitution variable ${cargo:Provides} used, but is not defined
dpkg-gencontrol: warning: Built-Using field of package pve-xtermjs: substitution variable ${cargo:Built-Using} used, but is not defined
dpkg-gencontrol: warning: package pve-xtermjs: substitution variable ${cargo:X-Cargo-Built-Using} used, but is not defined
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'pve-xtermjs' in '../pve-xtermjs_4.16.0-1_arm64.deb'.
make[1]: Leaving directory '/root/proxmox-backup-arm64/sources/pve-xtermjs'

**Comment by wofferl** [comment]
I forgot, you need to do a `make clean` before `make deb`.

**Comment by Leo-wq** [comment]
No difference. Same warnings only.

**Comment by Dentax** [comment]
Same for me. Did a `make clean` and then `make deb`

![image](https://user-images.githubusercontent.com/5037918/224494248-fdba16e1-d9c9-4d04-b7b4-ba0f1624a9a0.png)

**Comment by wofferl** [comment]
Ok, there is currently a problem with pve-xtermjs. The build termproxy binary is not packed in, which is easy to solve, but there is also a problem that the binary does not work anyway. 
It looks like a problem with missing dependencies. 
I'll take a look at it.
