### ISSUE TITLE
PBS client for arm64 installer 

### ISSUE THREAD

**Issue by Mrdindon** [wofferl/proxmox-backup-arm64#30]
Not an issue but a feature request :)

would you be able to add to your script (or make a separate one) to allow installation of pbs client on arm64 devices ?

I do have a few inovato quadra units I would like to backup to PBS. I’m sure this could be useful to many others :)

**Comment by wofferl** [comment]
I don't think I understand exactly your request.

This script is not an installation script. It is used to compile **all** the packages needed for Proxmox Backup on arm64 architecture.

If you have used it for your Proxmox Backup Server, you will find the proxmox-backup-client package in the packages directory. You then only need to distribute and install it on your clients if they use the same architecture and distribution.

If you have not used the script before, you first have to compile the packages on a compatible system with the script.

Unfortunately, the compilation process cannot be separated into server and client, so you always have to compile everything.

**Comment by Mrdindon** [comment]
That is correct. If you could come up with a script to compile the pbs client for arm64 that would be great :)
refering to that : https://forum.proxmox.com/threads/proxmox-backup-client-for-arm64.101091/

I do have PBS running on PVE (x86) but I do have a few arm64 IOT devices I would like to get backup on my PBS instance.
Not being familiar on how to compile anyhow, it would be great if you could make the same script you did for the PBS but for the client portion only ?

**Comment by wofferl** [comment]
As I said, the proxmox backup client is also compiled.

The script only calls the original proxmox compilation process and with that it is currently not possible to compile only the client.

You would have to contact Proxmox to have them do their build process separately.

**Comment by wofferl** [comment]
Ok, my fault, there seems to be an option. I will look what I can do.

**Comment by Mrdindon** [comment]
Hey no fault to nobody :) If you can do something , that's cool but your the boss !!!
What you already did for PBS on arm64 is pretty nice already :)
