### ISSUE TITLE
Support crosscompilation via docker buildx

### ISSUE THREAD

**Issue by heikok88** [wofferl/proxmox-backup-arm64#31]
Hello, thank you for your work.
I want to crosscompile the project without the need to setup qemu with an arm64-chroot.
This should be possible with the docker buildx command, see 
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

Best regards 
Heiko

**Comment by wofferl** [comment]
[simoncaron](https://github.com/simoncaron)  already provided a Dockerfile (https://github.com/wofferl/proxmox-backup-arm64/pull/29) for this.

`docker buildx build -o packages --platform linux/arm64`
