### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by albebert** [wofferl/proxmox-backup-arm64#32]
Hi, i'm trying to compile PBS client. 

but i've an error

`   Compiling pxar-bin v0.1.0 (/root/proxmox-backup-arm64/sources/proxmox-backup/pxar-bin)
    Finished release [optimized] target(s) in 21m 18s
warning: the following packages contain code that will be rejected by a future version of Rust: syn v0.12.15
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
touch ".do-cargo-build"
make -C docs
make[3]: Entering directory '/root/proxmox-backup-arm64/sources/proxmox-backup/docs'
../target/release/proxmox-backup-client printdoc > proxmox-backup-client/synopsis.rst
../target/release/dump-catalog-shell-cli > proxmox-backup-client/catalog-shell-synopsis.rst
../target/release/pxar printdoc > pxar/synopsis.rst
sphinx-build -t release -b man ./ output/man
make[3]: sphinx-build: No such file or directory
make[3]: *** [Makefile:83: man-pages] Error 127
make[3]: Leaving directory '/root/proxmox-backup-arm64/sources/proxmox-backup/docs'
make[2]: *** [Makefile:63: docs] Error 2
make[2]: Leaving directory '/root/proxmox-backup-arm64/sources/proxmox-backup'
dh_auto_build: error: make -j4 "INSTALL=install --strip-program=true" PROXY_USER=backup LIBDIR=/usr/lib/aarch64-linux-gnu returned exit code 2
make[1]: *** [debian/rules:25: override_dh_auto_build] Error 2
make[1]: Leaving directory '/root/proxmox-backup-arm64/sources/proxmox-backup'
make: *** [debian/rules:18: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
`

any idea ?

**Comment by wofferl** [comment]
There seems a problem creating docs.

Can you provide some info (system, distribution, cargo/rust version).

Also post the complete build output by redirecting it , so we better can see what's going wrong.

`./build.sh client >build.log 2>&1`

**Comment by albebert** [comment]
Hi,
system infos : 

Raspbian 11.7


cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: aarch64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Debian 11 (bullseye) [64-bit]


rustup 1.26.0 (5af9b9484 2023-04-05)

log : https://pastebin.com/u6fvFR5u
