### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by nmartinho** [wofferl/proxmox-backup-arm64#33]
Hi, 
I'm having problems compiling.

root@medeia:/opt/proxmox-backup-arm64# ./build.sh client
Download packages list from proxmox devel repository
Download packages list from pbs-no-subscription repository
Download dependencies
pve-eslint up-to-date
Install build dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pve-eslint' instead of '/opt/proxmox-backup-arm64/packages_build/pve-eslint_8.23.1-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

**The following packages have unmet dependencies:
 pve-eslint : Depends: nodejs (>= 12.22.12~dfsg) but 12.22.9~dfsg-1ubuntu3 is to be installed
E: Unable to correct problems, you have held broken packages.**

root@medeia:/opt/proxmox-backup-arm64# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

root@medeia:/opt/proxmox-backup-arm64# uname -r
5.15.92-bcm2711

root@medeia:/opt/proxmox-backup-arm64# cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=rpi4b
BOARD_NAME="Raspberry Pi 4"
BOARDFAMILY=bcm2711
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=1a8daf0
VERSION=23.02.2
LINUXFAMILY=bcm2711
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=stable
BRANCH=current

root@medeia:~# cargo -V
cargo 1.69.0 (6e9a83356 2023-04-12)

Thanks for the support.

**Comment by wofferl** [comment]
The downloaded dependencies are for debian/bullseye.

Can you try if you can build it for ubuntu/jammy.
```
git clone https://git.proxmox.com/git/pve-eslint.git
cd pve-eslint
make deb
```

**Comment by nmartinho** [comment]
More dependencies problems...

root@medeia:/opt/proxmox-backup-arm64/pve-eslint# make deb
[ -e src/lib/eslint.js ] || make src/lib/eslint.js
touch .any-eslint-js
rm -rf pve-eslint-8.41.0.tmp pve-eslint-8.41.0
mkdir pve-eslint-8.41.0.tmp
cp -a debian pve-eslint-8.41.0.tmp/
cp -a src/* pve-eslint-8.41.0.tmp/
echo "git clone git://git.proxmox.com/git/pve-eslint.git\\ngit checkout ffe585879b9e6e4c7f6f11a68fb3130fd655399c" > pve-eslint-8.41.0.tmp/debian/SOURCE
mv pve-eslint-8.41.0.tmp pve-eslint-8.41.0
cd pve-eslint-8.41.0; dpkg-buildpackage -b -uc -us
dpkg-buildpackage: info: source package pve-eslint
dpkg-buildpackage: info: source version 8.41.0-2
dpkg-buildpackage: info: source distribution bookworm
dpkg-buildpackage: info: source changed by Proxmox Support Team <support@proxmox.com>
dpkg-buildpackage: info: host architecture arm64
 dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 13) dh-nodejs pkg-js-tools (>= 0.8.11)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
make: *** [Makefile:45: pve-eslint_8.41.0-2_all.deb] Error 3

**Comment by wofferl** [comment]
Install the dependencies with `sudo apt -y build-dep .`

maybe an easier way is to try an older version. Try to install this version:
[pve-eslint_8.4.0-3_all.deb](http://download.proxmox.com/debian/devel/dists/bullseye/main/binary-amd64/pve-eslint_8.4.0-3_all.deb)

**Comment by wofferl** [comment]
Ok, the script tries to install the new version. I think that can be changed in the future.

Meanwhile you can change the PVE_ESLINT_VER in the script from:
`PVE_ESLINT_VER=(">=" "7.18.0-1")`
to
`PVE_ESLINT_VER=("=" "8.4.0-3")`

**Comment by nmartinho** [comment]
Things evolved after the version change, script runs for several time and stops.

...
Setting up xml-core (0.18+nmu1) ...
Setting up libfuse3-dev:arm64 (3.10.5-1build1) ...
Setting up debhelper (13.6ubuntu1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for sgml-base (1.30) ...
Setting up docutils-common (0.17.1+dfsg-2) ...
Processing triggers for sgml-base (1.30) ...
Setting up python3-docutils (0.17.1+dfsg-2) ...
dpkg-buildpackage: warning: invalid flag in DEB_BUILD_OPTIONS: 
dpkg-buildpackage: info: source package rust-proxmox-backup
dpkg-buildpackage: info: source version 2.4.2-1
dpkg-buildpackage: info: source distribution bullseye
dpkg-buildpackage: info: source changed by Proxmox Support Team <support@proxmox.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture arm64
dpkg-checkbuilddeps: error: Unmet build dependencies: fonts-lato fonts-open-sans graphviz latexmk proxmox-widget-toolkit-dev python3-sphinx texlive-fonts-extra texlive-fonts-recommended texlive-xetex xindy
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by wofferl** [comment]
Can you run the newest script version with -x and debug and post your build.log.

` bash -x ./build.sh client debug
`

**Comment by nmartinho** [comment]
@wofferl attached the build.log 
[build.log](https://github.com/wofferl/proxmox-backup-arm64/files/11582526/build.log)
