### ISSUE TITLE
Compilation is taking way too much

### ISSUE THREAD

**Issue by EricFROL** [wofferl/proxmox-backup-arm64#35]
Trying to compile in Armbian64, RPI 3B+, but it just gets stuck.
I have set up swap. Now has been compiling for 2 days, no new logs after the first 20 minutes. I also tried to compile with docker, same issue.
It always gets stuck in "lazycell" package.

Thank you in advance.

**Comment by wofferl** [comment]
Which Version you try to compile?
Is the newest rust Version installed?

Try again with the debug switch and post the build.log here.

**Comment by wofferl** [comment]
Feel free to reopen this issue and provide some info if the problem still exist.
