### ISSUE TITLE
Swapfile size restricted to 100M

### ISSUE THREAD

**Issue by OberfragGER** [wofferl/proxmox-backup-arm64#45]
Just for the docu (im using Raspi4) with the lastest Raspi OS (Bookworm).
The swapfile is restricted to 100M. If youre using fallocate, your running into

`fallocate: fallocate failed: Text file busy`

you see the status of the swapfile with:
`sudo service dphys-swapfile status`

To change that, you´ll edit
`sudo nano /etc/dphys-swapfile` to the Limit you want. But Max-Limit is 2048M
You´ll see (and change it) it in 
`nano /sbin/dphys-swapfile`

...just for the wiki.

**Comment by wofferl** [comment]
added, thanks.
