### ISSUE TITLE
proxmox-backup-client on pi5

### ISSUE THREAD

**Issue by muffem** [wofferl/proxmox-backup-arm64#46]
Hi wofferl!

I installed your prebuilt proxmox-backup-client package on a raspberry pi5 and did some backups on my proxmox-backup-server on another machine, which is working fine.
when I try browsing the backed up pxar/snapshot from the pi machine I get the following error:

proxmox-backup-client catalog shell host/xxx/2024-09-25T00:00:03Z xxx.pxar
Error: unable to read dynamic index 'xxx.pxar.didx' - Invalid argument (os error 22)

When I use the same command on another machine (non arm architecture), the interactive browsing shell starts.

**Comment by wofferl** [comment]
This is a problem with the standard kernel on rpi5, which uses 16k page sizes.
The problem and solution is described in #40 and [400 Bad Request on Raspberry Pi 5 (#40)](https://github.com/wofferl/proxmox-backup-arm64#400-bad-request-on-raspberry-pi-5-httpsgithubcomwofferlproxmox-backup-arm64issues40) .
