### ISSUE TITLE
request location files

### ISSUE THREAD

**Issue by william89731** [wofferl/proxmox-backup-arm64#47]
hi wofferl,
hi have build [widget temperature](https://github.com/william89731/proxmox-widget-temperature/tree/main) for pve 

![image](https://github.com/user-attachments/assets/b0002c35-8153-4250-aeaa-24d7c4b4acac)

where can i find files neccessary for building widget for pbs?

tx

**Comment by wofferl** [comment]
```
/usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js
/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
```

**Comment by william89731** [comment]
ok tx, 

In case I need more info, I'll reopen the issue
