### ISSUE TITLE
Question: Every time there is a new release I have to recompile and load from scratch?

### ISSUE THREAD

**Issue by logicito** [wofferl/proxmox-backup-arm64#51]
Is there a smoother upgrade path for existing installations? Thanks

**Comment by wofferl** [comment]
You can download per-compiled packages from the Release page or use the build.sh script to download/install automatically the newest version.

`./build.sh download`
or
`./build.sh install`

**Comment by logicito** [comment]
> You can download pre-compiled packages from the Release page or use the build.sh script to download/install automatically the newest version.
> 
> `./build.sh download` or `./build.sh install`

Thanks, If I select **./build.sh install** over an existing installation of proxmox-backup-server (previously installed by using ./build.sh install) what the build.sh script will do? it will only update the newer packages? it will operate like an apt update/upgrade?

**Comment by logicito** [comment]
> `./build.sh install` is an automation of downloading the newest pre-built packages from the github release page (it downloads only newer files) and is than doing an apt install of the downloaded files. If all packages already installed apt will do nothing, in case of newer files it will install/update these. It is the same way you would install packages on the terminal as described in the README.md
> 
> ## Install all needed packages
> ### Server
> ```
> sudo apt install \
>   ./libjs-extjs_*_all.deb \
>   ./libjs-qrcodejs_*_all.deb \
>   ./libproxmox-acme-plugins_*_all.deb \
>   ./pbs-i18n_*_all.deb \
>   ./proxmox-backup-docs_*_all.deb \
>   ./proxmox-backup-server_*_arm64.deb \
>   ./proxmox-mini-journalreader_*_arm64.deb \
>   ./proxmox-widget-toolkit_*_all.deb \
>   ./proxmox-termproxy_*_arm64.deb \
>   ./pve-xtermjs_*_all.deb
> ```
Thank you, this is great, you solution is amazing, thank you very much for creating and keeping it up to date!!!
