### ISSUE TITLE
Raspberry PI4 support ?

### ISSUE THREAD

**Issue by pomme2terree** [wofferl/proxmox-backup-arm64#7]
Hi, raspberrypi4 is supported?

**Comment by MAFLO321** [comment]
As far as I can tell: yes
I use it on my Raspberry Pi 4.
It is important to note that you need the Raspberry Pi OS 64 bit with bullseye (see [here](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit)) and to compile the project a sufficient amount of memory (RAM + SWAP) is required (see #4).

**Comment by MAFLO321** [comment]
@pomme2terree please close the issue if everything is settled for you.
