### ISSUE TITLE
User / password ???

### ISSUE THREAD

**Issue by jmbenevise** [wofferl/proxmox-backup-arm64#9]
Build and install went well.
I can access to the web interface.
Then, it fails with every combination of user / password I can try.

**Comment by MAFLO321** [comment]
As log as I know, the defaults of proxmox backup server is:

- Username: `root`
- Password: the password of your systems `root`-user
- Realm: `Linux PAM standard authentication`

You can add some additional users by cli (https://pbs.proxmox.com/docs/user-management.html).

**Comment by jmbenevise** [comment]
Ok.
Working. Thank you.
I just had to allow root to login.
